name: Start EC2
on:
  workflow_dispatch:
    
jobs:
  start-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Start EC2 instance if stopped
        run: |
          INSTANCE_ID="i-075c22a8bf3645192"
          echo "Checking instance state..."
          STATE=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" --query "Reservations[0].Instances[0].State.Name" --output text)
          echo "Current state: $STATE"
          if [ "$STATE" = "stopped" ]; then
            echo "Starting instance..."
            aws ec2 start-instances --instance-ids "$INSTANCE_ID" --output table
            echo "Waiting for EC2 to be running..."
            aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
            echo "EC2 started."
          elif [ "$STATE" = "running" ]; then
            echo "Instance is already running."
          else
            echo "Instance is in state: $STATE. No action taken."
          fi
          



  